[project]
name = "schoolproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "flask-alembic>=3.2.0",
    "flask-sqlalchemy>=3.1.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]
